2024-07-03 10:17:48,387 - mmseg - INFO - Loaded 1449 images
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/backbone/img_encoder.py", line 252, in __init__
    self.transformer = Transformer(
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/backbone/utils.py", line 230, in __init__
    x.item() for x in torch.linspace(0, drop_path_rate, layers)
TypeError: linspace(): argument 'steps' (position 3) must be int, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/inner_zegclip.py", line 54, in __init__
    super(InnerZegCLIP, self).__init__(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/segmentors/encoder_decoder.py", line 36, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: VPTCLIPVisionTransformer: linspace(): argument 'steps' (position 3) must be int, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/test.py", line 330, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/test.py", line 225, in main
    model = build_segmentor(cfg.model, test_cfg=cfg.get("test_cfg"))
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/zegenv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: InnerZegCLIP: VPTCLIPVisionTransformer: linspace(): argument 'steps' (position 3) must be int, not list
