/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0721 11:24:26.454536 52 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:24:45.481066 52 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:24:49.922800 52 init.cc:62] Found cuda archs: [86,]
[w 0721 11:24:50.025329 52 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:24:50.133131 52 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:24:50.440471 52 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x53/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0721 11:24:52.341900 08 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:24:52.372915 08 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:24:52.372995 08 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x53/AMDEPYC753232-x73/default
[i 0721 11:24:52.402769 08 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:24:52.430088 08 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:24:52.642389 08 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0721 11:24:53.206678 08 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:24:53.564836 08 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:24:56.695169 08 init.cc:62] Found cuda archs: [86,]
[w 0721 11:24:56.791128 08 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:24:56.890077 08 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:24:57.224741 40 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:24:57.249130 40 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:24:57.249204 40 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x53/AMDEPYC753232-x73/default
[i 0721 11:24:57.285767 40 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:24:57.311981 40 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:24:57.510845 40 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0721 11:24:58.113868 40 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:24:58.430089 40 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:25:01.576677 40 init.cc:62] Found cuda archs: [86,]
[w 0721 11:25:01.674297 40 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:25:01.772030 40 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:25:02.110837 76 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0721 11:25:02.142335 76 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0721 11:25:02.142411 76 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x53/AMDEPYC753232-x73/default
[i 0721 11:25:02.174496 76 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0721 11:25:02.204139 76 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0721 11:25:02.385913 76 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0721 11:25:02.987551 76 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0721 11:25:03.331229 76 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0721 11:25:06.426043 76 init.cc:62] Found cuda archs: [86,]
[w 0721 11:25:06.539931 76 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0721 11:25:06.649803 76 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0721 11:25:07.091802 52 compile_extern.py:339] Downloading cutt...
[i 0721 11:25:07.247997 52 compile_extern.py:352] installing cutt...
[i 0721 11:25:20.089756 52 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x53/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 5, in <module>
    from .segmentors import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/__init__.py", line 3, in <module>
    from .clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 5, in <module>
    from .segmentors import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 10, in <module>
    from jseg.utils.tokenizer import tokenize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/__init__.py", line 3, in <module>
    from .clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 152, in <module>
    _tokenizer = SimpleTokenizer()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 10, in <module>
    from jseg.utils.tokenizer import tokenize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 152, in <module>
    _tokenizer = SimpleTokenizer()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 72, in __init__
    merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 72, in __init__
    merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 5, in <module>
    from .segmentors import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/__init__.py", line 3, in <module>
    from .clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 10, in <module>
    from jseg.utils.tokenizer import tokenize
FileNotFoundError: [Errno 2] No such file or directory: 'project/clip_rc/bpe_simple_vocab_16e6.txt.gz'
FileNotFoundError: [Errno 2] No such file or directory: 'project/clip_rc/bpe_simple_vocab_16e6.txt.gz'
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 152, in <module>
    _tokenizer = SimpleTokenizer()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 72, in __init__
    merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'project/clip_rc/bpe_simple_vocab_16e6.txt.gz'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 15, in <module>
    import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/__init__.py", line 10, in <module>
    from models.segmentor.clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/models/segmentor/clip_rc.py", line 5, in <module>
    from jseg.ops import resize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/__init__.py", line 5, in <module>
    from .segmentors import *
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/__init__.py", line 3, in <module>
    from .clip_rc import CLIPRC
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 10, in <module>
    from jseg.utils.tokenizer import tokenize
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 152, in <module>
    _tokenizer = SimpleTokenizer()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/tokenizer.py", line 72, in __init__
    merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'project/clip_rc/bpe_simple_vocab_16e6.txt.gz'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-21_11:25:38
  host      : ae01116-176628.0-aisurrey15.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-21_11:25:38
  host      : ae01116-176628.0-aisurrey15.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-21_11:25:38
  host      : ae01116-176628.0-aisurrey15.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-21_11:25:38
  host      : ae01116-176628.0-aisurrey15.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
