/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[i 0728 14:05:38.389457 52 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0728 14:05:56.711660 52 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0728 14:05:56.883571 52 init.cc:62] Found cuda archs: [86,]
[w 0728 14:05:56.968331 52 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0728 14:05:58.151720 52 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0728 14:05:58.262583 52 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x72/AMDEPYC753232-x73/default/cu11.0.221_sm_86/custom_ops
[i 0728 14:06:00.114941 60 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0728 14:06:00.119752 60 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0728 14:06:00.119831 60 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x72/AMDEPYC753232-x73/default
[i 0728 14:06:00.125273 60 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0728 14:06:00.130067 60 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0728 14:06:00.283426 60 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0728 14:06:00.761654 60 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0728 14:06:00.943301 60 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0728 14:06:01.076125 60 init.cc:62] Found cuda archs: [86,]
[w 0728 14:06:01.152006 60 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0728 14:06:02.172891 60 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0728 14:06:02.349360 24 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0728 14:06:02.353602 24 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0728 14:06:02.353669 24 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x72/AMDEPYC753232-x73/default
[i 0728 14:06:02.358850 24 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0728 14:06:02.363973 24 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0728 14:06:02.500329 24 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0728 14:06:02.957456 24 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0728 14:06:03.145504 24 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0728 14:06:03.253475 24 init.cc:62] Found cuda archs: [86,]
[w 0728 14:06:03.329189 24 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0728 14:06:04.478736 24 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0728 14:06:04.648392 48 compiler.py:956] Jittor(1.3.8.5) src: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor
[i 0728 14:06:04.653192 48 compiler.py:957] g++ at /usr/bin/g++(7.5.0)
[i 0728 14:06:04.653264 48 compiler.py:958] cache_path: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x72/AMDEPYC753232-x73/default
[i 0728 14:06:04.658329 48 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0728 14:06:04.663382 48 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0728 14:06:04.796478 48 compiler.py:1011] cuda key:cu11.0.221_sm_86
[i 0728 14:06:05.266407 48 __init__.py:227] Total mem: 503.74GB, using 16 procs for compiling.
[i 0728 14:06:05.434171 48 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0728 14:06:05.559856 48 init.cc:62] Found cuda archs: [86,]
[w 0728 14:06:05.631836 48 compiler.py:1384] CUDA arch(86)>80 will be backward-compatible
[i 0728 14:06:06.635679 48 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0728 14:06:06.865781 52 compile_extern.py:339] Downloading cutt...
[i 0728 14:06:07.015894 52 compile_extern.py:352] installing cutt...
[i 0728 14:06:19.080371 60 compiler.py:34] Create cache dir: /user/HS400/ae01116/.cache/jittor/jt1.3.8/g++7.5.0/py3.9.19/Linux-4.18.0-4x72/AMDEPYC753232-x73/default/cu11.0.221_sm_86/cuda
[i 0728 14:06:37.279530 52 cuda_flags.cc:49] CUDA enabled.
[i 0728 14:06:37.858444 24 cuda_flags.cc:49] CUDA enabled.
[i 0728 14:06:37.885193 60 cuda_flags.cc:49] CUDA enabled.
[i 0728 14:06:37.902670 48 cuda_flags.cc:49] CUDA enabled.

Compiling Operators(1/16) used: 2.49s eta: 37.4s Compiling Operators(7/16) used: 3.49s eta: 4.49s Compiling Operators(16/16) used: 4.49s eta:    0s 

Compiling Operators(1/2) used: 3.35s eta: 3.35s Compiling Operators(2/2) used: 4.35s eta:    0s 
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/losses/cross_entropy_loss.py:55: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with Jittor official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(

Compiling Operators(1/6) used: 3.43s eta: 17.1s Compiling Operators(6/6) used: 4.43s eta:    0s 
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 83, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 72, in main
    runner = Runner()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/runner/runner.py", line 34, in __init__
    self.model = build_from_cfg(cfg.model, MODELS)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 33, in build_from_cfg
    module = obj_cls(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 34, in __init__
    super(CLIPRC, self).__init__(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/encoder_decoder.py", line 31, in __init__
    self.init_weights(pretrained=pretrained)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/encoder_decoder.py", line 59, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/clip_encoder_rlb.py", line 140, in init_weights
    checkpoint = jt.load(pretrained)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/__init__.py", line 1128, in load
    model_dict = safeunpickle(path)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/__init__.py", line 98, in safeunpickle
    model_dict = load_pytorch(path)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor_utils/load_pytorch.py", line 270, in load_pytorch
    result = unpickler.load()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor_utils/load_pytorch.py", line 109, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named '__torch__'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 83, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 72, in main
    runner = Runner()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/runner/runner.py", line 34, in __init__
    self.model = build_from_cfg(cfg.model, MODELS)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 33, in build_from_cfg
    module = obj_cls(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 34, in __init__
    super(CLIPRC, self).__init__(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/encoder_decoder.py", line 31, in __init__
    self.init_weights(pretrained=pretrained)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/encoder_decoder.py", line 59, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/clip_encoder_rlb.py", line 140, in init_weights
    checkpoint = jt.load(pretrained)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/__init__.py", line 1128, in load
    model_dict = safeunpickle(path)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/__init__.py", line 98, in safeunpickle
    model_dict = load_pytorch(path)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor_utils/load_pytorch.py", line 270, in load_pytorch
    result = unpickler.load()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor_utils/load_pytorch.py", line 109, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named '__torch__'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 83, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 72, in main
    runner = Runner()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/runner/runner.py", line 34, in __init__
    self.model = build_from_cfg(cfg.model, MODELS)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 33, in build_from_cfg
    module = obj_cls(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 34, in __init__
    super(CLIPRC, self).__init__(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/encoder_decoder.py", line 31, in __init__
    self.init_weights(pretrained=pretrained)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/encoder_decoder.py", line 59, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/clip_encoder_rlb.py", line 140, in init_weights
    checkpoint = jt.load(pretrained)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/__init__.py", line 1128, in load
    model_dict = safeunpickle(path)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/__init__.py", line 98, in safeunpickle
    model_dict = load_pytorch(path)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor_utils/load_pytorch.py", line 270, in load_pytorch
    result = unpickler.load()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor_utils/load_pytorch.py", line 109, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named '__torch__'
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 83, in <module>
    main()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py", line 72, in main
    runner = Runner()
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/runner/runner.py", line 34, in __init__
    self.model = build_from_cfg(cfg.model, MODELS)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/utils/registry.py", line 33, in build_from_cfg
    module = obj_cls(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/clip_rc.py", line 34, in __init__
    super(CLIPRC, self).__init__(**args)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/encoder_decoder.py", line 31, in __init__
    self.init_weights(pretrained=pretrained)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/segmentors/encoder_decoder.py", line 59, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/jseg/models/backbones/clip_encoder_rlb.py", line 140, in init_weights
    checkpoint = jt.load(pretrained)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/__init__.py", line 1128, in load
    model_dict = safeunpickle(path)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor/__init__.py", line 98, in safeunpickle
    model_dict = load_pytorch(path)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor_utils/load_pytorch.py", line 270, in load_pytorch
    result = unpickler.load()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/jittor_utils/load_pytorch.py", line 109, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named '__torch__'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/run_net.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-28_14:06:57
  host      : ae01116-177939.0-aisurrey16.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-28_14:06:57
  host      : ae01116-177939.0-aisurrey16.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-28_14:06:57
  host      : ae01116-177939.0-aisurrey16.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-28_14:06:57
  host      : ae01116-177939.0-aisurrey16.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
