/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:32: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:32: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:32: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:32: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 11, in <module>
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 11, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/apis/__init__.py", line 2, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/apis/__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/apis/inference.py", line 9, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/__init__.py", line 2, in <module>
    from mmseg.models import build_segmentor
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/backbones/__init__.py", line 7, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/backbones/__init__.py", line 7, in <module>
    from .fast_scnn import FastSCNN
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from .fast_scnn import FastSCNN
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from .ann_head import ANNHead
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/decode_head.py", line 11, in <module>
    from .decode_head import BaseDecodeHead
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/losses/__init__.py", line 6, in <module>
    from ..losses import accuracy
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/losses/__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 11, in <module>
    from mmseg.apis import set_random_seed, train_segmentor    
from .active_rotated_filter import active_rotated_filter
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/apis/__init__.py", line 2, in <module>
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
      File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/backbones/__init__.py", line 7, in <module>
ext_module = ext_loader.load_ext(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext_module = ext_loader.load_ext(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    from .fast_scnn import FastSCNN
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
Traceback (most recent call last):
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py", line 11, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/apis/__init__.py", line 2, in <module>
    from .decode_head import BaseDecodeHead
    ext = importlib.import_module('mmcv.' + name)  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/decode_head.py", line 11, in <module>

  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    ext = importlib.import_module('mmcv.' + name)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/apis/inference.py", line 9, in <module>
    from ..losses import accuracy
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/losses/__init__.py", line 6, in <module>
    from mmseg.models import build_segmentor
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/__init__.py", line 2, in <module>
    from .focal_loss import FocalLoss
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/backbones/__init__.py", line 7, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/__init__.py", line 2, in <module>
        ext_module = ext_loader.load_ext(return _bootstrap._gcd_import(name[level:], package, level)

  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
ModuleNotFoundError    : from .ann_head import ANNHeadNo module named 'mmcv._ext'    

  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
    ext = importlib.import_module('mmcv.' + name)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    from .decode_head import BaseDecodeHead
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/decode_heads/decode_head.py", line 11, in <module>
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'    
from ..losses import accuracy
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/losses/__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26) of binary: /mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/bin/python
Traceback (most recent call last):
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/fast/nobackup/scratch4weeks/ae01116/zegenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/fast/nobackup/users/ae01116/multi-modal-dissertation-uos/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-06_17:00:07
  host      : ae01116-179794.0-aisurrey14.surrey.ac.uk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-06_17:00:07
  host      : ae01116-179794.0-aisurrey14.surrey.ac.uk
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 28)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-06_17:00:07
  host      : ae01116-179794.0-aisurrey14.surrey.ac.uk
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-06_17:00:07
  host      : ae01116-179794.0-aisurrey14.surrey.ac.uk
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
